POST http://localhost:4000/clearance-actions/success
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1YzAwZmM2LWIwMDQtNGFiZS05ODRkLTdlN2ZmMzc5YWM0YyIsInJvbGUiOiJEUklWRVIiLCJlbWFpbCI6ImRyaXZlckBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2Nzg3NDk1MywiZXhwIjoxNzY3OTAzNzUzfQ.9YTMX3Q2aV0ILwpBLr6p_AZO5eGevfu3UYmMKd_FuQo

{
  "clearanceEventId": "01128f4e-47d1-4eb3-b503-3aac72d2363b"
}
