### Login as Office (get token)
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "office@mycouriersa.co.za",
  "password": "ChangeMe123!"
}

###

### Average Clearing Time - All Agents
GET http://localhost:4000/reports/average-clearing-time
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNDQzNywiZXhwIjoxNzY4ODUzMjM3fQ.lVn1DZsucdnBaJhDAOeie4XSC76E4-1I_2neuABLKxE

###

### Average Clearing Time - SUCCESS only
GET http://localhost:4000/reports/average-clearing-time?status=SUCCESS
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNDQzNywiZXhwIjoxNzY4ODUzMjM3fQ.lVn1DZsucdnBaJhDAOeie4XSC76E4-1I_2neuABLKxE

###

### Average Clearing Time - FAILED only
GET http://localhost:4000/reports/average-clearing-time?status=FAILED
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNDQzNywiZXhwIjoxNzY4ODUzMjM3fQ.lVn1DZsucdnBaJhDAOeie4XSC76E4-1I_2neuABLKxE

###

### Date Range Filter
GET http://localhost:4000/reports/average-clearing-time?from=2026-01-01&to=2026-01-31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNDQzNywiZXhwIjoxNzY4ODUzMjM3fQ.lVn1DZsucdnBaJhDAOeie4XSC76E4-1I_2neuABLKxE

###

### Per Branch Filter (Johannesburg example)
GET http://localhost:4000/reports/average-clearing-time?branchId=05c0f67a-bcc2-4428-a0b7-7086fb08b5d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNDQzNywiZXhwIjoxNzY4ODUzMjM3fQ.lVn1DZsucdnBaJhDAOeie4XSC76E4-1I_2neuABLKxE

###

### Trend by Day
GET http://localhost:4000/reports/average-clearing-time?trend=day
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNDQzNywiZXhwIjoxNzY4ODUzMjM3fQ.lVn1DZsucdnBaJhDAOeie4XSC76E4-1I_2neuABLKxE

###

### Trend by Month
GET http://localhost:4000/reports/average-clearing-time?trend=month
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNDQzNywiZXhwIjoxNzY4ODUzMjM3fQ.lVn1DZsucdnBaJhDAOeie4XSC76E4-1I_2neuABLKxE

###

### Export CSV (Excel)
GET http://localhost:4000/reports/average-clearing-time?export=csv
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNDQzNywiZXhwIjoxNzY4ODUzMjM3fQ.lVn1DZsucdnBaJhDAOeie4XSC76E4-1I_2neuABLKxE

###

### Report 2 - Overdue / Delayed per Agent
GET http://localhost:4000/reports/overdue-per-agent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNTYyNiwiZXhwIjoxNzY4ODU0NDI2fQ.nhEbP8z7p3Qcr0H6OA1BJCVO_A31K-I07B0gsR5ZFYA

### Date Range Filter
GET http://localhost:4000/reports/overdue-per-agent?from=2026-01-01&to=2026-01-31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNjU4MCwiZXhwIjoxNzY4ODU1MzgwfQ.ipgnVy76GcoCPX92rmeeXfUrUb3ZzDvXnJ5SJsTJ7Tw


### Per Branch
GET http://localhost:4000/reports/overdue-per-agent?branchId=05c0f67a-bcc2-4428-a0b7-7086fb08b5d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNjU4MCwiZXhwIjoxNzY4ODU1MzgwfQ.ipgnVy76GcoCPX92rmeeXfUrUb3ZzDvXnJ5SJsTJ7Tw


###  Trend by Day
GET http://localhost:4000/reports/overdue-per-agent?trend=day
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNjU4MCwiZXhwIjoxNzY4ODU1MzgwfQ.ipgnVy76GcoCPX92rmeeXfUrUb3ZzDvXnJ5SJsTJ7Tw

###  Trend by Month
GET http://localhost:4000/reports/overdue-per-agent?trend=month
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNjU4MCwiZXhwIjoxNzY4ODU1MzgwfQ.ipgnVy76GcoCPX92rmeeXfUrUb3ZzDvXnJ5SJsTJ7Tw

### Excel Export (CSV)
GET http://localhost:4000/reports/overdue-per-agent?export=csv
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNjU4MCwiZXhwIjoxNzY4ODU1MzgwfQ.ipgnVy76GcoCPX92rmeeXfUrUb3ZzDvXnJ5SJsTJ7Tw

### Report 3 Export Everything
GET http://localhost:4000/reports/waybills-manifests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNzQ5NCwiZXhwIjoxNzY4ODU2Mjk0fQ.3xmIdozfIxiVUF92oG_mMUEn5_3IYbdtALHeN8l-cYo

### Date Range Export
GET http://localhost:4000/reports/waybills-manifests?from=2026-01-01&to=2026-01-31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNzQ5NCwiZXhwIjoxNzY4ODU2Mjk0fQ.3xmIdozfIxiVUF92oG_mMUEn5_3IYbdtALHeN8l-cYo

### Agent Only
GET http://localhost:4000/reports/waybills-manifests?agentId=74aa8e7b-743a-4413-823c-c3cd58d9ff26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNzQ5NCwiZXhwIjoxNzY4ODU2Mjk0fQ.3xmIdozfIxiVUF92oG_mMUEn5_3IYbdtALHeN8l-cYo

### Open Events Only
GET http://localhost:4000/reports/waybills-manifests?status=OPEN
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyNzQ5NCwiZXhwIjoxNzY4ODU2Mjk0fQ.3xmIdozfIxiVUF92oG_mMUEn5_3IYbdtALHeN8l-cYo


### Report 5 Exceptions
GET http://localhost:4000/reports/exceptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyODcwNSwiZXhwIjoxNzY4ODU3NTA1fQ.T1U2UcRp10jJq7VEmKPz5fWW7u-JsIkMCIsyGTMLGNw

### Only Open Exceptions
GET http://localhost:4000/reports/exceptions?status=OPEN
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyODcwNSwiZXhwIjoxNzY4ODU3NTA1fQ.T1U2UcRp10jJq7VEmKPz5fWW7u-JsIkMCIsyGTMLGNw


### By Agent
GET http://localhost:4000/reports/exceptions?agentId=74aa8e7b-743a-4413-823c-c3cd58d9ff26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyODcwNSwiZXhwIjoxNzY4ODU3NTA1fQ.T1U2UcRp10jJq7VEmKPz5fWW7u-JsIkMCIsyGTMLGNw


### By Branch
GET http://localhost:4000/reports/exceptions?branchId=05c0f67a-bcc2-4428-a0b7-7086fb08b5d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyODcwNSwiZXhwIjoxNzY4ODU3NTA1fQ.T1U2UcRp10jJq7VEmKPz5fWW7u-JsIkMCIsyGTMLGNw


### Excel Export
GET http://localhost:4000/reports/exceptions?export=csv
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYjU1M2UzLWUzODUtNDQzNS05NTEwLWYwNjZmOTRjOWNmYSIsInJvbGUiOiJPRkZJQ0UiLCJlbWFpbCI6Im9mZmljZUBteWNvdXJpZXJzYS5jby56YSIsImlhdCI6MTc2ODgyODcwNSwiZXhwIjoxNzY4ODU3NTA1fQ.T1U2UcRp10jJq7VEmKPz5fWW7u-JsIkMCIsyGTMLGNw

